# Generated by Django 5.2.9 on 2025-12-15 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Только PDF, DOC, DOCX. Макс. 10 МБ', null=True, upload_to='resumes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Резюме'),
        ),
    ]
