# Generated by Django 5.2.9 on 2026-01-05 21:25

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('stack', models.CharField(blank=True, max_length=255, null=True, verbose_name='Technology stack (Python, React, Django и т.д.)')),
                ('relocation', models.BooleanField(default=False, verbose_name='Is relocation available')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('salary', models.PositiveIntegerField(blank=True, default=0)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_remote', models.BooleanField(blank=True, null=True)),
                ('required_experience', models.PositiveIntegerField(blank=True, default=0)),
                ('hard_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Технические навыки (Python, Django, SQL и т.д.)', size=None, verbose_name='Hard skills')),
                ('soft_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Мягкие навыки (коммуникация, лидерство, тайм-менеджмент)', size=None, verbose_name='Soft skills')),
                ('open', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique_for_date='created_at')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='profiles.employerprofile')),
            ],
            options={
                'verbose_name_plural': 'vacancies',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='VacancyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('status', models.CharField(choices=[('new', 'Новый отклик'), ('viewed', 'Просмотрен'), ('invited', 'Приглашён на собеседование'), ('rejected', 'Отклонён')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.jobseekerprofile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансию',
                'unique_together': {('vacancy', 'candidate')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='interested_candidates',
            field=models.ManyToManyField(blank=True, related_name='interested_in', through='vacancies.VacancyInterest', to='profiles.jobseekerprofile'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['slug'], name='vacancies_v_slug_f71efa_idx'),
        ),
    ]
