# Generated by Django 5.1.6 on 2025-02-11 20:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DateTimeField, sets when object is created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='DateTimeField, updates for every object update')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('salary', models.PositiveIntegerField(blank=True, default=0)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_remote', models.BooleanField(blank=True, null=True)),
                ('required_experience', models.PositiveIntegerField(blank=True, default=0)),
                ('required_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('open', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique_for_date='created_at')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='profiles.employerprofile')),
                ('interested_candidates', models.ManyToManyField(blank=True, related_name='interested_in', to='profiles.jobseekerprofile')),
            ],
            options={
                'verbose_name_plural': 'vacancies',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['slug'], name='vacancies_v_slug_f71efa_idx')],
            },
        ),
    ]
